### ISSUE TITLE
The plugin for file type xls is not installed. Please install pyexcel-xls

### ISSUE THREAD

**Issue by maltitco** [chfw/django-excel#1]
Should be ok because I have everything installed in the env:
![zrzut ekranu 2015-06-01 o 11 38 52](https://cloud.githubusercontent.com/assets/1561204/7910201/eacdec78-0852-11e5-9ca3-f9766089c9ec.png)

**Comment by chfw** [comment]
please try install this plugin to support xls file format

     pip install pyexcel-xls

for xlsx, then please install pyexcel-xlsx.

**Comment by maltitco** [comment]
I installed both: pyexcel-xls and pyexcel-xlsx


Error: The plugin for file type xlsx is not installed. Please install pyexcel-xls or pyexcel-xlsx

In the console server returns something else:

[01/Jun/2015 09:52:20]"GET /expenses/import/ HTTP/1.1" 200 13234
Depreciated usage. please use dest_file_name
[01/Jun/2015 09:53:06]"POST /expenses/import/ HTTP/1.1" 500 105424

**Comment by chfw** [comment]
Both of them should appear in your 'pip freeze' listing. In your screenshot, both of them are absent. So, could you double check?

I am going to remove the deprecation warning.

**Comment by maltitco** [comment]
This screenschot ist befor install pyexcel-xls and pyexcel-xlsx

now ist pip freeze:

Django==1.8
diff-match-patch==20121119
django-debug-toolbar==1.3.0
django-excel==0.0.2
django-import-export==0.2.8.dev0
future==0.14.3
jdcal==1.0
openpyxl==2.2.2
psycopg2==2.6
pyexcel==0.1.5
pyexcel-io==0.0.4
pyexcel-webio==0.0.2
pyexcel-xls==0.0.7
pyexcel-xlsx==0.0.6
sqlparse==0.1.15
tablib==0.10.0
texttable==0.8.3
wsgiref==0.1.2
xlrd==0.9.3
xlwt-future==0.8.0

**Comment by chfw** [comment]
Alright, you are there. The next thing is to import it:

    import pyexcel.ext.xls # or import pyexcel.ext.xlsx

see this example line: https://github.com/chfw/django-excel/blob/master/polls/views.py#L7

**Comment by maltitco** [comment]
Now work ;) - Thanks (I not imported pyexcel.ext.xls because PyCharm mark as unused).

I have a question abaut unique values:

can ignore the values which are already included in the database?

duplicate key value violates unique constraint "expenses_expensestype_expenses_type_key"
DETAIL:  Key (expenses_type)=(raz) already exists.

**Comment by chfw** [comment]
The limitation of the django-excel is the disability to detect value uniqueness and this is left for the developer-user to judge. For example, suppose you have an empty database, you imported your data once. But for some reason, you did the import once more. Under this situation, you may encounter unique key problems.

**Comment by srugano** [comment]
I'm still getting the same error : `Depreciated usage. please use dest_file_name` even though I've imported the pyexcel-xls and pyexcel-xlsx

**Comment by chfw** [comment]
This means  'out_file' parameter is used instead of dest_file_name in save_as or save_book_as functions. Please tell me the versions of pyexcel, pyexcel-webio, and django-excel. I will check.

**Comment by srugano** [comment]
django-excel==0.0.2
pyexcel==0.1.7
pyexcel-io==0.0.6
pyexcel-ods==0.0.9
pyexcel-webio==0.0.3
pyexcel-xls==0.0.7
pyexcel-xlsx==0.0.6
openpyxl==2.2.2

**Comment by chfw** [comment]
Your pyexcel related packages are up to date and should not have those depreciated warnings. I have to point out: those deprecation warning is not related to package imports. Is it coming from your own code?

**Comment by chfw** [comment]
Since the release of auto import feature of pyexcel 0.2.2, explicit imports of all pyexcel plugins in your code files are no longer required. However, you will still need to do pip install the plugins that you want to use.
