### ISSUE TITLE
Import empty rows

### ISSUE THREAD

**Issue by maltitco** [chfw/django-excel#2]
Why is it possible to import empty rows?
![zrzut ekranu 2015-06-02 o 14 35 52](https://cloud.githubusercontent.com/assets/1561204/7935881/b2abf2d0-0934-11e5-93c2-8c1fd5e2987d.png)

![zrzut ekranu 2015-06-02 o 14 32 30](https://cloud.githubusercontent.com/assets/1561204/7935847/7317a542-0934-11e5-8e99-1e195fb88e88.png)

They should not be skipped?

**Comment by chfw** [comment]
I have applied the fix there in pyexcel-io: https://github.com/chfw/pyexcel-io/issues/1

You can get it before I release it via:

     pip install git+https://github.com/chfw/pyexcel-io.git

Please let me know if it works for you

**Comment by maltitco** [comment]
Hey, that works fine, but only in a situation where the model does not have fields with the value "unique = True".

I tested a situation when the database is already one of the fields blank with the parameter "unique=True"
```
duplicate key value violates unique constraint "expenses_expensestype_expenses_type_key"
DETAIL:  Key (expenses_type)=() already exists.
```
 Therefore, I think a good solution would be to introduce a parameter that allowed to skip the already existing values.

**Comment by chfw** [comment]
By default, pyexcel give '' for empty cell but I think database treat null as empty. In your case, I guess it is because '' was given toexpenses_type and if '' is given at the second time, it will hit unique key problem. So, I suppose if pyexcel replace '' for None in your case, would it help?

**Comment by maltitco** [comment]
This would help only if the blank and duplicate were changed to None. This would eliminate the problem of unique.

**Comment by chfw** [comment]
tried, 'None' field does not work for Django. I have another solution and am working on it. Here is the issue tracker for it. https://github.com/chfw/pyexcel-io/issues/2

**Comment by chfw** [comment]
Please try the newer fix again:

     pip install git+https://github.com/chfw/pyexcel-io.git

Hope it make your use case smooth. 

I have to say it will be slow if your data size is huge but for now, I couldn't think of other faster way.

**Comment by maltitco** [comment]
Hello, I tested and working properly. In the case where the model have a unique value duplicate and blank lines are ignored. In the case of large amounts of data can be divided and import parcels.

Thank you very much!

**Comment by chfw** [comment]
pyexcel-io v0.0.5 with two fixes was just published to pypi.
