### ISSUE TITLE
Use verbose name

### ISSUE THREAD

**Issue by calon** [chfw/django-excel#3]
Is ther anyway to use verbose name in Django model instead of field names when customizing export file's column_names?

**Comment by chfw** [comment]
Yes, there is. Here is the example code::

    def export_data(request, atype):
        ....
        elif atype == "custom":
            question = Question.objects.get(slug='ide')
            query_sets = Choice.objects.filter(question=question)
            column_names = ['choice_text', 'id', 'votes']
            sheet = excel.pe.get_sheet(query_sets=query_sets, column_names=column_names)
            sheet.name_columns_by_row(0) # use the first row as column names
            sheet.colnames = ["X", "Y", "Z"] # please put verbose_name list here
            return excel.make_response(sheet, 'xls')

**Comment by calon** [comment]
Thanks!
