### ISSUE TITLE
Question: how to change file name and sheet name?

### ISSUE THREAD

**Issue by furins** [chfw/django-excel#5]
hello, I'm giving a try to the library but I can't find any hint on how to change 
1. the response filename (in chrome the file is named `download` with no extension)
2. the sheet name (it's `pyexcel_sheet1`)

how can I customize these two aspects? 
thanks in advance!

<hr>
here is my view's code:

    def exportExcel(request):
        qs = MyModel.objects.all()
        column_names = ['a', 'b']
        sheet = excel.pe.get_sheet(query_sets=qs, column_names=column_names)
        sheet.row[0] = ["a", "b"]
        return excel.make_response(sheet, 'xls')

**Comment by furins** [comment]
I answered myself the second question: it's very intuitive actually!

    sheet.name = "whatever you want"

but still I've no idea how to rename the file. I've tried

    return excel.make_response(sheet, 'xls', 200, filename="test.xls")

but it gives me an error:

    TypeError: save_as() got multiple values for argument 'filename'

**Comment by chfw** [comment]
What you can do is: 

    sheet.row[0] = ["a", "b"]
    response = excel.make_response(sheet, 'xls')
    response['Content-Disposition'] = 'attachment; filename="test.xls"'

Here is the [django documentation] (https://docs.djangoproject.com/en/1.8/ref/request-response/#telling-the-browser-to-treat-the-response-as-a-file-attachment)

make_reponse_xxx functions always return a HttpResponse object. With the returned response instance, you can do additional settings as above.

**Comment by furins** [comment]
so true! thank you!
