### ISSUE TITLE
XLS and XLSX export wont work.

### ISSUE THREAD

**Issue by JacobHonore** [chfw/django-excel#6]
I am having problems exporting to XLS and XLSX.
For XLS I get the following error:
Unexpected data type <class 'django.contrib.auth.models.User'>

For XLSX I get the following error:
Cannot convert hf to Excel

I have installed pyexcel-xls and xlsx.

Export to CSV works without any problems.

**Comment by chfw** [comment]
well, thanks for reporting. but I could help only when I have something like this one : https://github.com/chfw/pyexcel-ods/issues/2 . more details please

**Comment by chfw** [comment]
file export has been tested [here](https://github.com/chfw/django-excel/blob/master/testResponse.py#L98): these [file types] (https://github.com/chfw/django-excel/blob/master/testResponse.py#L25) including xls and xlsx, have been tested for export.

Please open this issue if you have more details
