### ISSUE TITLE
Filename of exported file

### ISSUE THREAD

**Issue by lorence-ingenuity** [chfw/django-excel#7]
How do i set the filename of the exported file? i used the save_as but didn't work

**Comment by chfw** [comment]
You can use 'dest_file_name', as in [this example from pyexcel](http://pythonhosted.org/pyexcel/tutorial_data_conversion.html#save-an-array-to-an-excel-sheet). and here is the documentation of [save_as](http://pythonhosted.org/pyexcel/generated/pyexcel.save_as.html#pyexcel.save_as)

**Comment by lorence-ingenuity** [comment]
i have this code:
book = excel.pe.Book({
    'As of {}'.format(timezone.now().date()): records
})
return excel.make_response(book, file_type)

but if i add book.save_as(filename) the filename will still always be "download'

i tried book.save_as(dest_file_name=filename) it will show an error.
save_as() got an unexpected keyword argument 'dest_file_name'

**Comment by chfw** [comment]
Let's clarify your save_as first. You are using book.save_as, hence you should read this one [book.save_as](http://pythonhosted.org/pyexcel/generated/pyexcel.Book.save_as.html#pyexcel.Book.save_as), whereas previous save_as is a modular function. You just need to call book.save_as("a_file.xls"). 

If you want to give it a download file name , you might read #5

**Comment by lorence-ingenuity** [comment]
Got it! Thanks!
