### ISSUE TITLE
Filename extension issue

### ISSUE THREAD

**Issue by florck** [chfw/django-excel#9]
In the following code : 

    class ExcelMixin(webio.ExcelInput):
         def _get_file_extension(self):
            extension = self.name.split(".")[1]
            return extension

you are considering that the filename will have only one dot. This is not always the case and I would recommend you take the last ( [-1] ) and not the second ( [1] ) element.
Otherwise for a file named tutu.12.xlsx, this will fail with error

> NotImplementedError at /import/
> Cannot read content of file type 12 from stream

This is very simple to correct and shouldn't lead to any side effect.

**Comment by chfw** [comment]
Indeed. Will take it on

**Comment by florck** [comment]
Thanks !
